name: connect_hockey
description: Connect.hockey

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+13

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  nb_utils: ^4.0.6
  flutter_svg: ^0.21.0-nullsafety.0
  cached_network_image: ^2.3.1
  simple_animations: ^3.0.1
  google_fonts: 2.0.0
  google_maps_flutter: ^2.0.1
  html: ^0.15.0
  intl: ^0.17.0
  geohash: ^0.2.1
  lottie: ^1.0.1
  lipsum: 1.0.1
  showcaseview: ^0.1.6
  charts_flutter: ^0.10.0
  flutter_staggered_animations: 1.0.0
  flutter_colorpicker: ^0.3.5
  geocoder: 0.2.1
  geolocator: ^7.0.1
  geolocator_platform_interface: ^2.0.0
  plugin_platform_interface: ^2.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  provider: ^4.3.2+1
  google_sign_in: ^5.0.7
  apple_sign_in: ^0.1.0
  image_picker: ^0.8.2
  form_field_validator: ^1.1.0
  get: ^4.3.4
  age: ^0.0.1
  flutter_facebook_auth: ^3.5.0

  #firebase
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_auth_web: ^1.1.2
  firebase_auth_platform_interface: ^4.2.2
  cloud_firestore: ^2.1.0
  firebase_storage: ^10.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.11.5
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/Connect_hockey/logo_connect_hockey_flutter_color.png"
    #flutter packages pub run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/theme1/
    - images/theme6/
    - images/theme13/
    - images/theme10/
    - images/LikeButton/image/
    - images/smartDeck/
    - images/Connect_hockey/
    - images/Connect_hockey/logo_connect_hockey_flutter-accueil.png
    - images/Connect_hockey/logo_connect_hockey_flutter_color.png
    - images/theme6/t6_ic_list.svg
    - images/theme6/goalie_icon.svg
    - images/theme6/visualization_icon.svg
    - images/theme6/t6_ic_activity.svg
    - images/theme13/t13_ic_map.svg
    - images/theme13/t13_trophy.svg
    - images/theme6/background_connect_hockey_logo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

